FROM gcr.io/google_appengine/jetty:latest

# Add application code under /var/lib/jetty/webapps directory
ADD target/spring-boot-jetty-docker-web-1.0.0-SNAPSHOT/ /var/lib/jetty/webapps/spring-boot-jetty-docker-web

