# This file configures the spring-boot-jetty-docker application frontend. The frontend serves
# public web traffic.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-jetty-docker
  labels:
    app: spring-boot-jetty-docker

#   https://cloud.google.com/kubernetes-engine/docs/pods/
spec:
  replicas: 3

  template:
    metadata:
      labels:
        app: spring-boot-jetty-docker
        tier: frontend

    spec:
      containers:
      - name: spring-boot-jetty-docker
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/[GCLOUD_PROJECT]/spring-boot-jetty-docker

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always

        # The spring-boot-jetty-docker process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
